server:
  applicationConnectors:
  - type: http
    port: 50050
  adminConnectors:
  - type: http
    port: 50150

stylingPort: 50051
deliveryPort: 50054
stylingHost: "localhost"
deliveryHost: "localhost"

applicationTagsYamlFile: "./shopping/applicationTags.yaml"
wfReportingConfigYamlFile: "./wfReportingConfig.yaml"